const mockEvents = {
  city: {
    id: 1007700,
    city: "München",
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257
  },
  events:[
    {
      created: 1563825339000,
      duration: 9000000,
      id: "263370107",
      name: "Microservices mit dem MicroProfile 3.x",
      rsvp_limit: 80,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1566925200000,
      local_date: "2019-08-27",
      local_time: "19:00",
      updated: 1563825339000,
      utc_offset: 7200000,
      waitlist_count: 79,
      yes_rsvp_count: 80,
      venue: {
      id: 26266792,
      name: "adesso AG",
      lat: 53.54524230957031,
      lon: 9.950983047485352,
      repinned: false,
      address_1: "Große Elbstraße 36",
      city: "Hamburg",
      country: "de",
      localized_country_name: "Deutschland"
      },
      group: {
      created: 1387402147000,
      name: "Java User Group Hamburg",
      id: 11500362,
      join_mode: "open",
      lat: 53.54999923706055,
      lon: 10,
      urlname: "jug-hamburg",
      who: "Mitglieder",
      localized_location: "Hamburg, Deutschland",
      state: "",
      country: "de",
      region: "de_DE",
      timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/de-DE/jug-hamburg/events/263370107/",
      description: "<p>Wer Microservices in Java entwickeln möchte, muss nicht zwangsläufig zu Spring Boot greifen. Es lohnt ein Blick auf alternative Frameworks, die in zunehmender Anzahl verfügbar sind und bezüglich ihrer Funktionalität stark aufholen. So schreitet auch die Entwicklung des MicroProfiles weiter voran. In beeindruckender Geschwindigkeit wurden zahlreiche APIs entwickelt, die (nicht nur) für die Entwicklung von Microservices sehr hilfreich sind.<br/>Hierzu zählen die Unterstützung von Metriken, Health Checks, Fault Tolerance und JSON Web Tokens. Für den Einsatz im Projekt kann aus unterschiedlichen Implementierungen wie TomEE, Thorntail oder OpenLiberty gewählt werden. In dieser Live-Coding-Session wird der praktische Einsatz von MicroProfile anhand eines Praxisbeispiels demonstriert.<br/> <br/> <br/>Referent:<br/>Thilo Frotscher arbeitet als freiberuflicher Softwarearchitekt und Trainer. Als Experte für Enterprise Java und Systemintegration unterstützt er seine Kunden überwiegend durch Entwicklung, Reviews oder die Durchführung von Schulungen. Thilo ist (Co-)Autor mehrerer Bücher in den Bereichen Java EE, (Web) Services und Systemintegration, hat zahlreiche Fachartikel verfasst und spricht regelmäßig auf Fachkonferenzen und Schulungsveranstaltungen oder bei Java User Groups.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1596623415000,
      duration: 28800000,
      id: "272375614",
      name: "Classic Southern Route - Classic Sunday Ride ",
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1596960000000,
      local_date: "2020-08-09",
      local_time: "10:00",
      updated: 1596629400000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 12,
      venue: {
      id: 26920287,
      name: "Perlacher Forst",
      lat: 48.089385986328125,
      lon: 11.574456214904785,
      repinned: true,
      city: "Perlacher Forst",
      country: "de",
      localized_country_name: "Germany"
      },
      is_online_event: false,
      group: {
      created: 1431768559000,
      name: "Munich Social Cyclists",
      id: 18601603,
      join_mode: "open",
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: "munich-social-cyclists",
      who: "Social cyclists",
      localized_location: "München, Germany",
      state: "",
      country: "de",
      region: "en_US",
      timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/munich-social-cyclists/events/272375614/",
      description: "<p>Due to some very disruptive construction works on most of the S-Bahn lines, we're going to meet at an unusual place this Sunday.</p> <p>Please be at the north entrance to Perlacher Forest before 10:00 am.</p> <p><a href=n\"https://goo.gl/maps/D5SMxvihM9n1CKQe6n\" class=n\"linkifiedn\">https://goo.gl/maps/D5SMxvihM9n1CKQe6</a></p> <p>Or, meet me at Deutsches Museum - Ludwigsbrücke side, where the Giant Propeller use to be - at 0930.</p> <p>Route planning is still in progress, but you can assume this will be approx. 60 km with only moderate hills.</p> <p>There will be 3 biergarden stops - all of which are well known to the group.</p> <p>The route might look something like this:<br/><a href=n\"https://www.bikemap.net/en/r/6934667n\" class=n\"linkifiedn\">https://www.bikemap.net/en/r/6934667</a></p> <p>As usual, please read the n\"What we're aboutn\" page, and be sure you have checked over your bike before Sunday.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1596547466000,
      duration: 61200000,
      id: "272355710",
      name: "Auf die Gotzenalm über alten vergessenen Steig am Königssee",
      rsvp_limit: 3,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1596859200000,
      local_date: "2020-08-08",
      local_time: "06:00",
      updated: 1596547466000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
      id: 23387472,
      name: " U-Bahn Giselastraße",
      lat: 48.155120849609375,
      lon: 11.586016654968262,
      repinned: false,
      address_1: "Giselastraße",
      city: "München",
      country: "de",
      localized_country_name: "Germany"
      },
      is_online_event: false,
      group: {
      created: 1594909978000,
      name: "Raus aus der Komfortzone - Trau Dich",
      id: 33972537,
      join_mode: "open",
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: "Raus-aus-der-Komfortzone-Trau-Dich",
      who: "Die Mutigen",
      localized_location: "München, Germany",
      state: "",
      country: "de",
      region: "en_US",
      timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/Raus-aus-der-Komfortzone-Trau-Dich/events/272355710/",
      description: "<p>Hallo Ihr Mutigen.<br/>Ich gehe am Samstag von Schönau am Königssee auf die Gotzenalm. Jedoch möchte ich hier einen alten vergessenen Steig wieder finden, der am Ostufer des Königssees entlang zur behelfsmäßigen Schiffs Haltestelle „Kessel“ führt. Von dort aus geht der Reitsteig dann zur Alm auf der wir eine gemütliche Brotzeit einnehmen können. Je nach Fitness und Lust können von hier aus auch noch andere Ziele angesteuert werden. Wer also Lust hat auf dieses Abenteuer ist herzlich eingeladen mitzufahren.<br/>Voraussetzungen:<br/>Gutes Schuhwerk, Trittsicherheit, gute Kondition und Lust auf ein wenig Abenteuer. Ich habe im Auto noch drei Plätze frei.<br/>LG euer Toni</p> ",
      visibility: "public",
      member_pay_fee: false
      }
  ]
};

export {mockEvents};
