const mockEvents = {
  "city": {
    "id": 1007700,
    "city": "München",
    "lat": 48.14,
    "lon": 11.58,
    "state": "",
    "country": "de",
    "zip": "meetup3",
    "member_count": 1257
  },
  "events": [
    {
      "created": 1596198612000,
      "duration": 7200000,
      "id": "272273081",
      "name": "Sunday Soccer Mixed Training @ Ostpark",
      "rsvp_limit": 14,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1596365100000,
      "local_date": "2020-08-02",
      "local_time": "12:45",
      "updated": 1596231209000,
      "utc_offset": 7200000,
      "waitlist_count": 10,
      "yes_rsvp_count": 14,
      "venue": {
        "id": 24455556,
        "name": "Ostpark",
        "lat": 48.112064361572266,
        "lon": 11.640679359436035,
        "repinned": true,
        "address_1": "Ostpark",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1407922218000,
        "name": "Soccer Munich",
        "id": 16360972,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Soccer-Munich",
        "who": "Player",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Soccer-Munich/events/272273081/",
      "description": "<p>Due to the new regulations we can have a training session, but I will have to collect the contact data of each attendee and we have to keep 1,5 meters distance.</p> <p>Location: <a href=n\"https://goo.gl/maps/9xz9pYYaRSpn\" class=n\"linkifiedn\">https://goo.gl/maps/9xz9pYYaRSp</a></p> <p>In the event that you have to call an ambulance for someone who has been injured while playing soccer, please provide the operator the following address: Staudingerstrasse 65.</p> ",
      "how_to_find_us": "https://goo.gl/maps/9xz9pYYaRSp",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1596009568000,
      "duration": 7200000,
      "id": "272223549",
      "name": "Kickball Season Opener",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1596366000000,
      "local_date": "2020-08-02",
      "local_time": "13:00",
      "rsvp_close_offset": "PT18H",
      "updated": 1596009845000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 12,
      "venue": {
        "id": 24048363,
        "name": "English Garden",
        "lat": 48.15223693847656,
        "lon": 11.595105171203613,
        "repinned": true,
        "address_1": "English Garden",
        "city": "Munich",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1469016785000,
        "name": "Munich Kickball",
        "id": 20204783,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Munchen-Kickball",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Munchen-Kickball/events/272223549/",
      "description": "<p>Hi All! With the loosening of social restrictions, and the freedom of team sports again, we’d like to open our kickball season! Wahoo!!! 🎉 👏🏼</p> <p>We will play in the open fields between Seehaus and Chinese Tower (please see map pin).</p> <p>In order to make this game viable, we need a minimum of 12 committed players.<br/>Please fee free to wear a facemask if it makes you feel more comfortable. 😷<br/>We will adhere to all present Corona rules. Instead of high fives, let’s give elbow or fist bumps. 🤙🏼😜</p> <p>After the game we’ll head to a beer garden to celebrate this season opener! 🍻</p> <p>Note: If we do not have enough players to make the game work, we will head to a beer garden any way. 😉</p> <p>In the event of rain, we will push to a weekday evening and/or play next weekend. 👍🏻</p> ",
      "visibility": "public",
      "member_pay_fee": false
    }
  ]
}

export { mockEvents };
